### PR TITLE
Feature/header bar UI

### PR DESCRIPTION
**Pull request by xijiewang4**
took out infobutton and moved it into a separate file
added PBL divider for every overview page
merged views to add into native navigation bar

### CODE REVIEW

**Review by bmorris-revacomm — CHANGES_REQUESTED** [review]
Nice! Can we move all buttons that are not the info button down so they more closely match the figma design?

**Comment by xijiewang4** [comment]
> Nice! Can we move all buttons that are not the info button down so they more closely match the figma design?

yeah i think so, right now they are part of the native navigation bar items but i think i will just need to put them in a separate view instead or apply padding on them somehow

**Comment by bmorris-revacomm** [comment]
> > Nice! Can we move all buttons that are not the info button down so they more closely match the figma design?
> 
> yeah i think so, right now they are part of the native navigation bar items but i think i will just need to put them in a separate view instead or apply padding on them somehow

Nevermind, don't worry about it! I think we are actually going to keep it this way and do some small updates later

**Comment by bmorris-revacomm** [comment]
> > > Nice! Can we move all buttons that are not the info button down so they more closely match the figma design?
> > 
> > 
> > yeah i think so, right now they are part of the native navigation bar items but i think i will just need to put them in a separate view instead or apply padding on them somehow
> 
> Nevermind, don't worry about it! I think we are actually going to keep it this way and do some small updates later

If you can just remove the dividers, I think you're good!

**Comment by bmorris-revacomm** [comment]
It looks like there's still one divider left on the recent sorties list view!

**Comment by xijiewang4** [comment]
> It looks like there's still one divider left on the recent sorties list view!

ok yeah I think that is the reason i added all those dividers in the first place, the List view added a divider, im gonna see if i can remove it or hide it

**Comment by bmorris-revacomm** [comment]
> > It looks like there's still one divider left on the recent sorties list view!
> 
> ok yeah I think that is the reason i added all those dividers in the first place, the List view added a divider, im gonna see if i can remove it or hide it

Oooooh interesting haha. Sounds good, thanks!

**Review by jbethanco — CHANGES_REQUESTED** [review]
After tapping an event and then returning, the "Event" title is gone. 


Simulator Screen Recording - iPad Pro (9 7-inch) - 2021-05-20 at 16 45 32

**Review by bmorris-revacomm — APPROVED** [review]
looks good!

**Review by jbethanco — APPROVED** [review]

**Pull request merged**
