### PR TITLE
Looks like the launch screen has to be at the top level.

### PR DESCRIPTION
**Pull request by Pete-Hoch**
OK, I think I have it this time.

(Can't drop iOS 13 support soon enough.)

### CODE REVIEW

**Review by cbrech — APPROVED** [review]

**Comment by petermisik** [comment]
Why are we using a storyboard in swiftUI?  I thought one of the main reasons was to get away from using them.

**Comment by jbethanco** [comment]
Just for launch on iOS 13.

**Comment by cbrech** [comment]
@petermisik the launch/splash screen on iOS 13. Not any of the actual app.

**Comment by petermisik** [comment]
Thank you for the clarification

**Review by petermisik — COMMENTED** [review]
Nice and clean.

**Pull request merged**
