### PR TITLE
PBS-278: Conversion from whole minutes to tenths of an hour 781 logic.

### PR DESCRIPTION
**Pull request by Pete-Hoch**
This is the conversion logic from the 781 form to turn minutes into tenths of an hour.

I change the input and output to numbers (instead of strings) because that seemed more flexible. 

I did not hook this up to be used anywhere, but I think that is OK as another task.

### CODE REVIEW

**Comment by jbethanco** [comment]
Would this be better to keep where it is at and bring it over if/when we need to use it?

**Comment by Pete-Hoch** [comment]
> Would this be better to keep where it is at and bring it over if/when we need to use it?

I think it's when we need it. Is there an issue of bringing it over now? So it's there when we need it.

**Comment by petermisik** [comment]
I vote for bringing it.

**Comment by jbethanco** [comment]
> > Would this be better to keep where it is at and bring it over if/when we need to use it?
> 
> I think it's when we need it. Is there an issue of bringing it over now? So it's there when we need it.

No huge deal. It's just odd practice to bring over unused code and tests on unused code.  I think it would be more proper to bring it over when and if it is needed.  Just seems like something that should be done in place upon implementation.

**Review by jbethanco — APPROVED** [review]

**Review by petermisik — COMMENTED** [review]
Looks good.

**Pull request merged**
