### PR TITLE
Disallows third party keyboard

### PR DESCRIPTION
**Pull request by jbethanco**
To silence NowSecure warning.

### CODE REVIEW

**Comment by Pete-Hoch** [comment]
Are we sure that we want to do this?
We should check to see if anyone uses third party keyboards.
We can also change the score in Now Secure if we are just worried about the report.

**Comment by jbethanco** [comment]
> Are we sure that we want to do this?
> We should check to see if anyone uses third party keyboards.
> We can also change the score in Now Secure if we are just worried about the report.

EFB iPads are locked down. Doubt anyone is using a custom keyboard. If they are, they can contact us, and we can allow per identifier.

**Comment by Pete-Hoch** [comment]
> > Are we sure that we want to do this?
> > We should check to see if anyone uses third party keyboards.
> > We can also change the score in Now Secure if we are just worried about the report.
> 
> EFB iPads are locked down. Doubt anyone is using a custom keyboard. If they are, they can contact us, and we can allow per identifier. "To silence NowSecure warning." was poor word choice. This is about a vulnerability.

Sounds good. Looking...

**Review by Pete-Hoch — APPROVED** [review]
Looks good & works great!

**Pull request merged**
