### PR TITLE
Feature/pbs 1025 tails

### PR DESCRIPTION
**Pull request by petermisik**
Summary:
     Pull in Tail number to populate serial number, mds, harm location, and unit charged.  Serial number text field now contains a drop down feature and as the user types, the list shrinks.

### CODE REVIEW

**Comment by cbrech** [comment]
Screen Shot 2021-07-01 at 11 44 18 AM

I like it overall, couple things. 
Can you sort these?



Screen Shot 2021-07-01 at 11 46 22 AM
Can we add some placeholder text like "Type to search" or something like that

**Comment by cbrech** [comment]
Can you make the rows a bit taller so they are easier to click on with a finger?

**Review by jbethanco — CHANGES_REQUESTED** [review]
image
Really think we need some kind of border/drop shadow or something around the edges here. It just cuts into the view without providing much context for what it is autocompleting for. 

When used in dark mode... nothing shows up... but the border looks better.
image

**Comment by jbethanco** [comment]
Also... Seems clicking outside the dropdown should have dismiss the list. It persists and a user must scroll around.
Simulator Screen Recording - -  _iPad Pro (9 7-inch) - 2021-07-01 at 21 16 34

**Comment by petermisik** [comment]
Closing PR.  Will generate new one when refactoring is complete.

**Pull request closed without merging**
