### PR TITLE
Make Mission Data section two columns.

### PR DESCRIPTION
**Pull request by Pete-Hoch**
This is close to Figma. I was not able to change the background for the form and so the colored islands looked odd.

Rachael gave a verbal OK to go with this for now.

Also grouped and cleaned up the new view group files.

### CODE REVIEW

**Review by jbethanco — COMMENTED** [review]
The results look great. 
Is there an easy way to merge parallel branches that were working on the several files that were renamed?

**Review by jbethanco — APPROVED** [review]

**Comment by Pete-Hoch** [comment]
> Is there an easy way to merge parallel branches that were working on the several files that were renamed?

When renaming/moving files in git, it remembers where they came from, so when you merge (or rebase) the main branch onto a parallel branch, git will do the heavy lifting in the diff.

**Comment by jbethanco** [comment]
Cool

**Comment by jbethanco** [comment]
I think XCode integrated git doesn't like heavy lifting. :)

**Comment by Pete-Hoch** [comment]
> I think XCode integrated git doesn't like heavy lifting. :) On Wed, Jan 20, 2021 at 6:55 PM John Bethancourt < jbethancourt.ctr@revacomm.com> wrote:
> […](#)

Happy to do demos on command line git. It's super fun.

**Comment by jbethanco** [comment]
lol. I might need it. So far okay. It's funny... you do the exact same
thing in the command line as you try in xcode... Xcode fails, command line
works.

**Comment by Pete-Hoch** [comment]
> lol. I might need it. So far okay. It's funny... you do the exact same thing in the command line as you try in xcode... Xcode fails, command line works.
> […](#)

I have never used Xcode to do anything but edits to resolve conflicts. I always do my git commands from Terminal.

**Pull request merged**
