### PR TITLE
PBS-621 and 513 - Allow user to give feedback

### PR DESCRIPTION
**Pull request by jbethanco**
- Add a "CollectorWebView" which loads the destination page of a JIRA feedback collector.
- Inject javascript into webpage to add the build number and version so the user does
not have to manually enter it.
- Add action sheet off of the info button with two options:
1. View Release Notes
2. Submit a Problem

### CODE REVIEW

**Comment by Pete-Hoch** [comment]
Screen Shot 2021-02-19 at 7 41 18 AM

The window does not automatically close. (At least it has not after a minute.)

**Comment by jbethanco** [comment]
> Screen Shot 2021-02-19 at 7 41 18 AM
> 
> The window does not automatically close. (At least it has not after a minute.)

We have no control over that part of the Jira collector. 
Do you have a suggestion on way to fix without a Jira callback?

**Comment by Pete-Hoch** [comment]
That is a sadness, we can take it as a bug and deal later. Have added this to Jira.

https://jira.il2.dso.mil/browse/PBS-635

**Review by Pete-Hoch — APPROVED** [review]
Cool.

**Review by petermisik — APPROVED** [review]
I like the idea of the invisible button.  Good work around.  As always, yay for more WebKit.

**Comment by jbethanco** [comment]
> That is a sadness, we can take it as a bug and deal later. Have added this to Jira.
> 
> https://jira.il2.dso.mil/browse/PBS-635

Thanks.

**Pull request merged**
