### PR TITLE
Change Sortie Types for Tankers

### PR DESCRIPTION
**Pull request by Adam-Roney581**
### What this PR does :thinking: 
Changes sortie types when the sortie is a tanker. Remove "Airdrop" and "Special Ops Low Level II". Add "Air Refueling Tanker"
### Resolves :white_check_mark: 
[PBS-2427](https://jira.il2.dso.mil/browse/PBS-2427)

### Testing Items :microscope: 
- [ ] Change mds to K and test the sortie types
- [ ] Change mds back to something else (Ex: C-17) and verify sortie types come back
- [ ] Add some sortie types that aren't included in tanker, change mds back to "K" and verify that they are removed 
- [ ] Verify in the pdf that the right sortie types appear

### CODE REVIEW

**Comment by tsanders88** [comment]
animation seems slower when tanker selected for sortie types

**Comment by tsanders88** [comment]
opened an old mission, was already tanker
turned everything off, then switched to nontanker
airland and air refueling were already on
probably not the desired behavior

suggestion: when switching between MDS only keep displaying active sortie types that they have in common

**Comment by tsanders88** [comment]
new feedback from -10 and -46 folks: only remove Airdrop and Special Ops Low Level II

In addition the -46 wants to add "Tanker" type and might want to clarify "Air Refueling" is for receiver.

Probably need to discuss, but makes sense to go ahead and address as rework in this Issue i think

**Comment by Adam-Roney581** [comment]
Hold until I can test the api changes

**Comment by Adam-Roney581** [comment]
Ready

**Review by thardie2 — APPROVED** [review]

**Pull request merged**
