### PR TITLE
Add DataProtection Capability Entitlement.

### PR DESCRIPTION
**Pull request by jbethanco**
Need to update the provisioning profile in developer.apple.com to match prior to this, so this can pass tests/ work.

### CODE REVIEW

**Comment by cbrech** [comment]
Is this a result of the NowSecure scan?

**Comment by jbethanco** [comment]
> Is this a result of the NowSecure scan?
I think the initial NowSecure scan caught it. 
Assuming it will be a NowSecure issue as the sqlite is readable with the app terminated.

**Comment by cbrech** [comment]
Go ahead and turn it on. Let's see if it break the pipeline (I doubt it)

**Comment by jbethanco** [comment]
> Go ahead and turn it on. Let's see if it break the pipeline (I doubt it)

image

👆 Github Actions PBL profile is showing Data Protection Enabled... not importing?

**Comment by jbethanco** [comment]
> > Go ahead and turn it on. Let's see if it break the pipeline (I doubt it)
> 
> image
> 
> 👆 Github Actions PBL profile is showing Data Protection Enabled... not importing?

image
🤔

**Comment by jbethanco** [comment]
> > Go ahead and turn it on. Let's see if it break the pipeline (I doubt it)
> 
> image
> 
> 👆 Github Actions PBL profile is showing Data Protection Enabled... not importing?

I think the problem is around here:

**Pull request closed without merging**
