### PR TITLE
Change Navigation

### PR DESCRIPTION
**Pull request by jbethanco**
Nav view is in.
Reads from core data, but does not write
Lots to do

### CODE REVIEW

**Comment by Pete-Hoch** [comment]
As we talked about, let's get a scroller under the form cards on the main page and reduce the (i) to just the current link.

**Comment by jbethanco** [comment]
> As we talked about, let's get a scroller under the form cards on the main page and reduce the (i) to just the current link.

Done.

**Review by petermisik — COMMENTED** [review]
I like it. I think putting the old files in a folder is good for continuity.

**Review by Pete-Hoch — APPROVED** [review]
Let's get going.

**Pull request merged**
