### PR TITLE
Remove cookies and destroy session on subsequent login attempts.

### PR DESCRIPTION
**Pull request by jbethanco**

### CODE REVIEW

**Review by petermisik — APPROVED** [review]
I like clearing the cookie cache on failure.

**Comment by cbrech** [comment]
Still getting errors on the simulator when I set debug to the prod url. Put a log dump in MM

**Comment by cbrech** [comment]
I think there are two different things, the repeated login error (which this helps) and the calls timing out

**Comment by jbethanco** [comment]
> I think there are two different things, the repeated login error (which this helps) and the calls timing out

Increasing the timeouts.

**Pull request merged**
