### PR TITLE
Fix/enabled updating flight time

### PR DESCRIPTION
**Pull request by bmorris-revacomm**
created this PR because I have to leave soon and this way people can look at it. It doesn't seem to be saving correctly to the json - I'm wondering if this has to do with the CrewMember model properties being optionals? If anyone knows what the issue is, please let me know!

- enabled updating flight time (not flight conditioning yet)
- updated unit test for updating crewMembers

### CODE REVIEW

**Comment by jbethanco** [comment]
> created this PR because I have to leave soon and this way people can look at it. It doesn't seem to be saving correctly to the json - I'm wondering if this has to do with the CrewMember model properties being optionals? If anyone knows what the issue is, please let me know!
> 
> * enabled updating flight time (not flight conditioning yet)
> * updated unit test for updating crewMembers

Need to fix the json problem before merge. Did it give an error?

**Comment by Pete-Hoch** [comment]
> > created this PR because I have to leave soon and this way people can look at it. It doesn't seem to be saving correctly to the json - I'm wondering if this has to do with the CrewMember model properties being optionals? If anyone knows what the issue is, please let me know!
> > 
> > * enabled updating flight time (not flight conditioning yet)
> > * updated unit test for updating crewMembers
> 
> Need to fix the json problem before merge. Did it give an error?

We are not currently promising persistent data migration. (Not even from 0.1.0 to the next version.) Is that what your json problem is in reference to?

**Comment by Pete-Hoch** [comment]
Getting these errors:

2020-12-21 15:06:44.406950-1000 Logging[74285:6841067] ERROR: FlightListViewController prepare(for: - Unknown identifier '<Logging.AircrewViewController: 0x7f8bac727820>'
2020-12-21 15:06:44.413587-1000 Logging[74285:6841067] ERROR: FlightListViewController prepare(for: - Unknown identifier '<Logging.MissionDataViewController: 0x7f8bac4078f0>'
2020-12-21 15:06:44.454644-1000 Logging[74285:6841067] ERROR: FlightListViewController prepare(for: - Unknown identifier '<Logging.AircrewDataViewController: 0x7f8bac413c10>'

**Comment by Pete-Hoch** [comment]
Screen Shot 2020-12-21 at 3 38 45 PM

Do we have some default Mission Data now? I didn't type this in.

**Comment by jbethanco** [comment]
> Screen Shot 2020-12-21 at 3 38 45 PM
> 
> Do we have some default Mission Data now? I didn't type this in.

I think that is coming from the old (and new) file existence check in the tests. We'll need to delete the file in the teardown to prevent.

**Comment by Pete-Hoch** [comment]
Screen Shot 2020-12-21 at 5 18 31 PM

Two characters fit fine when not editing, but we can only see one character while editing.

Screen Shot 2020-12-21 at 5 19 23 PM

And a duration like 10.2 does not fit in the non editing state either.

**Comment by bmorris-revacomm** [comment]
@Pete-Hoch From what I could tell when I was trying to debug, it is updating the flight time and conditions properly for the crew member, but it's just not persisting - if I close the app and reopen it, the data is gone

**Review by jbethanco — APPROVED** [review]
Don't see any problems.

**Pull request merged**
