### PR TITLE
Fix/side menu navigation

### PR DESCRIPTION
**Pull request by bmorris-revacomm**
- removed segmented control
- side menu now navigates to overview, mission data, aircrew list, and aircrew data

### CODE REVIEW

**Comment by bmorris-revacomm** [comment]
also renamed some files

**Comment by cbrech** [comment]
@bmorris-revacomm looks like there is no way to close the side menu

**Comment by bmorris-revacomm** [comment]
@cbrech oops! I forgot to check constraints on the 9.7 ipad - I'll fix it. In the meantime, it should work on the 12.9

**Comment by cbrech** [comment]
Cool, it also has merge conflicts

**Review by cbrech — APPROVED** [review]

**Pull request merged**
