### PR TITLE
PBS-831 new crew edit view with delete

### PR DESCRIPTION
**Pull request by Pete-Hoch**
This has the new UI we talked about in this mornings meeting.

Delete is still broken, but I wanted to get this out and get feedback on the screen changes while continuing to look into the crash when deleting an aircrew member.

### CODE REVIEW

**Review by jbethanco — APPROVED** [review]
If the save fix is working for you, i think it is good to go.

**Comment by Pete-Hoch** [comment]
I had to add one more change and nil out the person_ in the crewline before delting the crewline. 

This works, but I am not sure if we now have a dangeling reference to something in the database.

**Comment by jbethanco** [comment]
No need to nil the person. It's automatic as the delete rule on Crewline is at to nullify.

**Comment by Pete-Hoch** [comment]
> No need to nil the person. It's automatic as the delete rule on Crewline is set to nullify.

Well if I don't do it we crash. So I'm not sure what that means.

**Pull request merged**
