### PR TITLE
Add progress indicators and the logic.

### PR DESCRIPTION
**Pull request by petermisik**

### CODE REVIEW

**Review by cbrech — CHANGES_REQUESTED** [review]
On the simulator, using prod...after 5 minutes I am still seeing circles next to each org name.

**Comment by cbrech** [comment]
fully locked up, had to force restart app

**Comment by petermisik** [comment]
On my smaller set, I'm not seeing the long wait.  Will you add me to a few more units so I can see you sample set?

**Comment by petermisik** [comment]
Closing this PR as we're reworking the endpoint that may fix this.

**Pull request closed without merging**
