### PR TITLE
Add new figma design colors

### PR DESCRIPTION
**Pull request by Pete-Hoch**
Bring over the design colors from Figma and add then as their new names.

Did not switch over to them other than making Primary our accent color.

### CODE REVIEW

**Review by petermisik — COMMENTED** [review]
I like it.  The IconText idea is really cool.

**Review by jbethanco — APPROVED** [review]
Works good. Does the IconText lock in our alignment problems though?

**Comment by Pete-Hoch** [comment]
IconText was not actually an addition in this PR and I think Beth already removed it due to the alignment issues.

**Comment by bmorris-revacomm** [comment]
I didn't remove the file, but I did change those two fields because they were the only ones affected. Do you think I should remove the file?

**Comment by Pete-Hoch** [comment]
> I didn't remove the file, but I did change those two fields because they were the only ones affected. Do you think I should remove the file?

I don't think that is necessary. It's a nice item where we can use it.

**Pull request merged**
