### PR TITLE
Update Form781+PDF.swift

### PR DESCRIPTION
**Pull request by jbethanco**
Add print to print info:
printInfo.duplex = .shortEdge

### CODE REVIEW

**Review by Pete-Hoch — COMMENTED** [review]
Unfortunately this makes no difference for my printer.

HP Laser.

**Comment by jbethanco** [comment]
> Unfortunately this makes no difference for my printer.
> 
> HP Laser.

Does it need to be long edge? I'm not sure what output you are expecting.

**Comment by Pete-Hoch** [comment]
> > Unfortunately this makes no difference for my printer.
> > HP Laser.
> 
> Does it need to be long edge? I'm not sure what output you are expecting.

I get long edge binding with or without this change.
I also get long edge binding if I set my orientation to landscape.
Everything is long edge binding.

**Review by petermisik — COMMENTED** [review]
I get the same.  We're looking for short edge because you would naturally turn the form (left) on the short edge and have all of the images facing the same way.

**Comment by jbethanco** [comment]
I'm thinking this may be pdf issue. 
However, our pdf prints the same duplex way as the official version. (if you flip on the short edge, then form upside down)

**Pull request closed without merging**
