### PR TITLE
refactor sortie card, refactor sortie info view

### PR DESCRIPTION
**Pull request by bmorris-revacomm**
- refactor sortie card
- refactor sortie info view
- clean code

### CODE REVIEW

**Comment by Pete-Hoch** [comment]
This loos like it has some of "Fix/frame label #279" mixed in.

**Comment by bmorris-revacomm** [comment]
Yes, I just fixed it!

**Review by jbethanco — APPROVED** [review]
Runs/looks nice.

**Review by Pete-Hoch — APPROVED** [review]
Sweet.

**Pull request merged**
