### PR TITLE
Fix/feedback form colors - (PBS-1144)

### PR DESCRIPTION
**Pull request by bmorris-revacomm**
- update feedback form colors when switching between light/dark mode

### CODE REVIEW

**Review by petermisik — APPROVED** [review]
Love the color scheme and the find on the permissions.

**Review by cbrech — CHANGES_REQUESTED** [review]
Is there a way we can prevent the form from asking for camera stuff? I'm wary of adding the camera permission, I think that will complicate the cyber review process.

**Comment by bmorris-revacomm** [comment]
> Is there a way we can prevent the form from asking for camera stuff? I'm wary of adding the camera permission, I think that will complicate the cyber review process.

Unfortunately, I don't think so. There doesn't seem to be a way to remove the "take photo" option from the menu without also removing the photo library option. What we could do is open the feedback form in a separate web browser instead of pulling it up in the app with webkit, but if we do that, we don't have a way to auto-fill with what version and build number they are on (unless we have a way to have jira allow auto-filling form fields with url parameters)

**Comment by bmorris-revacomm** [comment]
removed camera permission request - going to leave this PR as just updating form colors

**Review by cbrech — APPROVED** [review]

**Pull request merged**
