### PR TITLE
make more fields editable

### PR DESCRIPTION
**Pull request by Pete-Hoch**
Since Serial Number is on the form card, I made it save changes to Core Data too, and found a better way to make sure we update the Form Card on return.

(The only way, if you returned before committing the text field, the card did not update.)

### CODE REVIEW

**Review by jbethanco — COMMENTED** [review]
Let's talk about this one tomorrow. I'm a little worried about updating the database on everyfield instead of a batch update with the . onDisappear similar to how we load it. 
There's also some wonkyness with ObservedObject that got ironed out with StateObject in iOS14 we should look at.

**Comment by Pete-Hoch** [comment]
> Let's talk about this one tomorrow. I'm a little worried about updating the database on everyfield instead of a batch update with the . onDisappear similar to how we load it.
> There's also some wonkyness with ObservedObject that got ironed out with StateObject in iOS14 we should look at.

Sounds good. The onDisappear gets called on load too, it's not like viewWillDisappear. But I don't know how much thrash there is when you change Core Data. I thought it was efficient and didn't do too much, but it's new to me. I was just kind of exited it worked.

**Comment by jbethanco** [comment]
> > Let's talk about this one tomorrow. I'm a little worried about updating the database on everyfield instead of a batch update with the . onDisappear similar to how we load it.
> > There's also some wonkyness with ObservedObject that got ironed out with StateObject in iOS14 we should look at.
> 
> Sounds good. The onDisappear gets called on load too, it's not like viewWillDisappear. But I don't know how much thrash there is when you change Core Data. I thought it was efficient and didn't do too much, but it's new to me. I was just kind of exited it worked.

This seems it will be fun. :) 
https://developer.apple.com/forums/thread/655338

**Comment by jbethanco** [comment]
> > Let's talk about this one tomorrow. I'm a little worried about updating the database on everyfield instead of a batch update with the . onDisappear similar to how we load it.
> > There's also some wonkyness with ObservedObject that got ironed out with StateObject in iOS14 we should look at.
> 
> Sounds good. The onDisappear gets called on load too, it's not like viewWillDisappear. But I don't know how much thrash there is when you change Core Data. I thought it was efficient and didn't do too much, but it's new to me. I was just kind of exited it worked.

Think I might have tracked down the problem. 
Calling .onDisappear or .onAppear on a Form Section, causes all sorts of extra calls. We'll need to due a Binding to the vars on the section from the Main form, and then do the saving from the main form's .onDisappear. These were the tests: Went to the main form, and left the main form to Flights: 


2021-01-15 07:29:55.469943-1000 Logging[965:21010] Main Form Appear
2021-01-15 07:29:55.482344-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.488296-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.492743-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.496892-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.500879-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.505221-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.509650-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.555234-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.555500-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.555729-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.555912-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.556091-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.556258-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.556442-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.563112-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.565083-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.568738-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.572414-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.576201-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.579289-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.583194-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.586481-1000 Logging[965:21010] MDS Appear
2021-01-15 07:29:55.606523-1000 Logging[965:21010] [Warning] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a table view cell's content view. We're considering the collapse unintentional and using standard height instead. Cell: <SwiftUI.ListCoreCellHost: 0x123861e00; baseClass = UITableViewCell; frame = (0 604.5; 736 44); autoresize = W; layer = <CALayer: 0x600003aab880>>
2021-01-15 07:29:55.612152-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:29:55.615695-1000 Logging[965:21010] MDS Appear
appear
appear
appear
appear
2021-01-15 07:30:21.952319-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952454-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952541-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952636-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952710-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952801-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952869-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.952941-1000 Logging[965:21010] MDS Disappear
2021-01-15 07:30:21.953085-1000 Logging[965:21010] Main Form Disappear

**Comment by Pete-Hoch** [comment]
> > > Let's talk about this one tomorrow. I'm a little worried about updating the database on everyfield instead of a batch update with the . onDisappear similar to how we load it.
> > > There's also some wonkyness with ObservedObject that got ironed out with StateObject in iOS14 we should look at.
> > 
> > 
> > Sounds good. The onDisappear gets called on load too, it's not like viewWillDisappear. But I don't know how much thrash there is when you change Core Data. I thought it was efficient and didn't do too much, but it's new to me. I was just kind of exited it worked.
> 
> Think I might have tracked down the problem.
> Calling .onDisappear or .onAppear on a Form Section, causes all sorts of extra calls. We'll need to due a Binding to the vars on the section from the Main form, and then do the saving from the main form's .onDisappear. These were the tests: Went to the main form, and left the main form to Flights:
> 
> 2021-01-15 07:29:55.469943-1000 Logging[965:21010] Main Form Appear
> 2021-01-15 07:29:55.482344-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.488296-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.492743-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.496892-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.500879-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.505221-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.509650-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.555234-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.555500-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.555729-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.555912-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.556091-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.556258-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.556442-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.563112-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.565083-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.568738-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.572414-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.576201-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.579289-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.583194-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.586481-1000 Logging[965:21010] MDS Appear
> 2021-01-15 07:29:55.606523-1000 Logging[965:21010] [Warning] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a table view cell's content view. We're considering the collapse unintentional and using standard height instead. Cell: <SwiftUI.ListCoreCellHost: 0x123861e00; baseClass = UITableViewCell; frame = (0 604.5; 736 44); autoresize = W; layer = <CALayer: 0x600003aab880>>
> 2021-01-15 07:29:55.612152-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:29:55.615695-1000 Logging[965:21010] MDS Appear
> appear
> appear
> appear
> appear
> 2021-01-15 07:30:21.952319-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952454-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952541-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952636-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952710-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952801-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952869-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.952941-1000 Logging[965:21010] MDS Disappear
> 2021-01-15 07:30:21.953085-1000 Logging[965:21010] Main Form Disappear

Does the same thing happen in AircrewDetail where the section is wrapped in a VStack?

**Pull request closed without merging**
